title: WELSH Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mmhmm.github.io
baseurl: /just-the-docs-test/cy

aux_links:
  Home: /en/index.html
  Cartref: /cy/index.html
  GitHub: https://mmhmm.github.com/just-the-docs-test

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607
